### PR TITLE
Messages v1

### PR DESCRIPTION
**Pull request by Esinko**
First version of complete messages support

### CODE REVIEW

**Comment by Esinko** [comment]
You may review and test this. But editing / sending drafts and forwarding / replying is not done yet.

**Review by developerfromjokela — COMMENTED** [review]
Did you count in that parent could have so called PasswdID? So r_guardian_passwd?

**Comment by Esinko** [comment]
The issue will be addressed in the next patch, which will be tomorrow.

**Comment by Esinko** [comment]
Everything should be done and patched, so this pr is ready to be merged. Please test this as thoroughly as possible as there have been multiple request lib changes and bug fixes which could affect other features of OpenWilma as well.

**Comment by Esinko** [comment]
I'll merge this tomorrow if nobody has anything to add

**Review by PaulusParssinen — APPROVED** [review]
_Looks_ good to me :shipit:

**Comment by Esinko** [comment]
Nice! I'll merge now.

**Pull request merged**
