### PR TITLE
Login errors patch & Printouts v1

### PR DESCRIPTION
**Pull request by Esinko**
Printouts support v1 and some login fixes

### CODE REVIEW

**Comment by Esinko** [comment]
Also fixed some issues with news support

**Comment by developerfromjokela** [comment]
Error handling could be better (not just for login). If you put `?format=json`, all errors will be in JSON format.

**Comment by Esinko** [comment]
Api error handling is something I have not yet gotten into

**Review by ahnl — APPROVED** [review]

**Review by developerfromjokela — APPROVED** [review]
Approved

**Comment by developerfromjokela** [comment]
Merging

**Pull request merged**
